### ISSUE TITLE
which node version is required?

### ISSUE THREAD

**Issue by kandroid29** [Kruithne/nwjs-installer#1]
I have installed nwjs-installer via npm install nwjs-installer -g,
after I installed it and run nwjs-installer --version, it gives me SyntaxError:

/usr/local/lib/node_modules/nwjs-installer/index.js:2
import { parse } from '@kogs/argv';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

what is missing to use it?
ps: I was running it on WSL ubuntu on Windows 11

**Comment by Kruithne** [comment]
It looks like the version of Node you're using doesn't support ESM. `nwjs-installer` is tested against Node 18 and Node 19, so I would suggest pinning Node 19 as your minimum version.

IIRC installing Node using the Ubuntu package manager installs a largely out-dated version. If you use the command below, it should install Node 18.

```
curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt-get install -y nodejs    
```

Node 18 is the current LTS. You can change the 18 for a more recent version if you wish. The current latest-features release is Node 20.

**Comment by kandroid29** [comment]
> It looks like the version of Node you're using doesn't support ESM. `nwjs-installer` is tested against Node 18 and Node 19, so I would suggest pinning Node 19 as your minimum version.
> 
> IIRC installing Node using the Ubuntu package manager installs a largely out-dated version. If you use the command below, it should install Node 18.
> 
> ```
> curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
> sudo apt-get install -y nodejs    
> ```
> 
> Node 18 is the current LTS. You can change the 18 for a more recent version if you wish. The current latest-features release is Node 20.

Upgrading to Node 18 and it works, Thank you very much
